use_frameworks!

target 'LoginKit_Example' do

  pod 'ILLoginKit', :path => '../'

  target 'LoginKit_Tests' do
    inherit! :search_paths
  end
  
  pod 'Kingfisher'
  pod 'FTIndicator'
  pod 'FTPickerView'
  pod 'FTImageSize'

  pod 'Alamofire', '~> 4.4'
  
  pod 'ApiAI/Core' #, :path => '../'
  pod 'ApiAI/VoiceRequest' #, :path => '../'
  pod 'ApiAI/UIKit' #, :path => '../'
  pod 'ApiAI/ResponseMapping' #, :path => '../'
  pod 'MBProgressHUD'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
